### ISSUE TITLE
faboritoak ikuskatu

### ISSUE THREAD

**Issue by ealdekoa** [UPV-EHU-Bilbao/AnttonEndikaAnder#13]
datu basean gordeta dauden faboritoak interfaze graficoan erakutzi

**Comment by juananpe** [comment]
Gauza bera, deskribapena falta (laburra bada ere)

**Comment by antton95** [comment]
fav botoioa sakatzerakoan hautatutako twitterreko erabiltzailearen fav-ak ikuskatu

**Comment by antton95** [comment]
faboritoak jtablean ikuskatzen dira
